hotel/bookings/urls.py
from django.urls import path

from . import views

app_name = 'bookings'

urlpatterns = [
    path('', views.rooms, name='rooms'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:room_id>/payment/', views.payment, name='payment'),
]

hotel/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from . forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='core:login'), name='logout')
]

hotel/hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('bookings/', include('bookings.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/bookings/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
    

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.name
    
class Room(models.Model):
    category = models.ForeignKey(Category, related_name='rooms', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='room_images', blank=True, null=True)
    is_booked = models.BooleanField(default=False)
    rented_by = models.ForeignKey(User, related_name='rooms', on_delete=models.CASCADE)
    rented_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class Payment(models.Model):
    user = models.ForeignKey(User, related_name='payments', on_delete=models.CASCADE)
    room = models.ForeignKey(Room, related_name='payments', on_delete=models.CASCADE)
    amount = models.FloatField()
    payment_date = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=50, choices=[
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        ('bank_transfer', 'Bank Transfer'),
    ])

    def __str__(self):
        return f'{self.user} - {self.room.name} - {self.amount}'



hotel/core/models.py
from django.db import models

# Create your models here.

hotel/bookings/forms.py
from django import forms

from . models import Payment

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        exclude = ['user', 'room']
        fields = ('user', 'amount', 'payment_method')
        widgets = {
            'user': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'amount': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'payment_method': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

hotel/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'password': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

        username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
        email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'Your email address',
            'class': 'w-full py-4 px-6 rounded-xl'
    }))
        password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'password': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
        password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'password': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


hotel/bookings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from . forms import PaymentForm
from . models import Category, Room

def rooms(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    rooms = Room.objects.filter(is_booked=False)

    if category_id:
        rooms = rooms.filter(category_id=category_id)

    if query:
        rooms = rooms.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'bookings/rooms.html', {
        'rooms': rooms,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })

def detail(request, pk):
    room = get_object_or_404(Room, pk=pk)
    related_rooms = Room.objects.filter(category=room.category, is_booked=False).exclude(pk=pk)[0:3]

    return render(request, 'bookings/detail.html', {
        'room': room,
        'related_rooms': related_rooms
    })


@login_required
def payment(request, room_id):
    room = get_object_or_404(Room, pk=room_id)

    if request.method == 'POST':
        form = PaymentForm(request.POST)

        if form.is_valid():
            payment = form.save(commit=False)
            payment.room = room
            payment.user = request.user
            payment.save()

            room.is_booked = True
            room.save()

            print("Form is valid, payment processed, and room status updated.")
            return redirect('bookings:detail', pk=room.id)
        else:
            print(form.errors)
    else:
        form = PaymentForm()

    return render(request, 'bookings/form.html', {
        'form': form,
        'title': 'Payment',
    })

@login_required
def delete(request, pk):
    room = get_object_or_404(Room, pk=pk, rented_by=request.user)
    room.delete()

    return redirect('core:index')

hotel/core/views.py
from django.shortcuts import render, redirect
from . forms import SignupForm
from django.contrib import messages

def index(request):
    return render(request, 'core/index.html')

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Registration was successful, you can now login.')

            return redirect('core:login')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
            'form': form
        })


hotel/bookings/templates/bookings/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ room.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ room.image.url }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ room.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ room.price }}</p>
        <p class="text-gray-500"><strong>Hotel Description: </strong>{{ room.description }}</p>
    
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ room.description }}
            </p>
        {% endif %}

            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>Book now to get 50% discount.</p>

                <a href="{% url 'bookings:payment' room.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Book Now</a>
                
            </div>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Similar rooms</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for room in related_rooms %}
            <div>
                <a href="{% url 'bookings:detail' room.id %}">
                    <div>
                        <img src="{{ room.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ room.name }}</h2>
                        <p class="text-gray-500">Price: {{ room.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

hotel/bookings/templates/bookings/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

hotel/bookings/templates/bookings/rooms.html
{% extends 'core/base.html' %}

{% block title %}Rooms{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'bookings:rooms' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find your suitable stay...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'bookings:rooms' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'bookings:rooms' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for room in rooms %}
                    <div>
                        <a href="{% url 'bookings:detail' room.id %}">
                            <div>
                                <img src="{{ room.image.url }}" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ room.name }}</h2>
                                <p class="text-gray-500">Price: {{ room.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

hotel/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Hotel Booking</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Hotel Booking</a>

            <div class="space-x-6">
                <a href="{% url 'bookings:rooms' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <form action="{% url 'core:logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</button>
                    </form>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">This is a hotel booking full stack project, built using django.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

hotel/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

hotel/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for room in rooms %}
            <div>
                <a href="{% url 'room:detail' room.id %}">
                    <div>
                        <img src="{{ room.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ room.name }}</h2>
                        <p class="text-gray-500">Price: {{ room.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.rooms.count }} rooms</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

hotel/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>
{% endblock %}

hotel/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>
{% endblock %}